# Generated by Django 4.2 on 2023-11-21 12:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("type", models.CharField(max_length=200)),
                ("lowPrice", models.DecimalField(decimal_places=2, max_digits=6)),
                ("highPrice", models.DecimalField(decimal_places=2, max_digits=6)),
                ("priceCurrency", models.CharField(max_length=50)),
                ("offer_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("type", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=200)),
                ("color", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(null=True)),
                ("itemcondition", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("releaseDate", models.DateTimeField(auto_now=True)),
                ("sku", models.UUIDField(unique=True)),
                ("product_url", models.URLField()),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "offers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.offer"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated", "-created"],
            },
        ),
    ]
