# Generated by Django 4.2 on 2023-10-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=200)),
                ("lowPrice", models.DecimalField(decimal_places=2, max_digits=6)),
                ("highPrice", models.DecimalField(decimal_places=2, max_digits=6)),
                ("priceCurrency", models.CharField(max_length=50)),
                ("offer_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=200)),
                ("color", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="path/filename")),
                ("itemcondition", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("releaseDate", models.DateTimeField(auto_now=True)),
                ("sku", models.UUIDField(unique=True)),
                ("product_url", models.URLField()),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "offers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.offer"
                    ),
                ),
            ],
        ),
    ]
