# Generated by Django 4.2 on 2024-01-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="room",
            new_name="shoe",
        ),
    ]
