# Generated by Django 4.2 on 2024-01-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_product_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="body",
            field=models.TextField(default="abc"),
            preserve_default=False,
        ),
    ]
